server:
  port: 8761
spring:
  application:
    name: eureka-1
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false